/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 ./src/models/avatar/models/646d9dcdc8a5f5bddbfac913_Notextures.glb --transform --debug --types 
Files: ./src/models/avatar/models/646d9dcdc8a5f5bddbfac913_Notextures.glb [997.82KB] > 646d9dcdc8a5f5bddbfac913_Notextures-transformed.glb [578.1KB] (42%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei/native";
import { GLTF } from "three-stdlib";
import AVATAR_MODEL from "../models/avatar/models/646d9dcdc8a5f5bddbfac913/result.obj";
import { useGraph, useLoader } from "@react-three/fiber/native";
import React, { useRef } from "react";
import { MTLLoader } from "three/examples/jsm/loaders/MTLLoader";
import { OBJLoader } from "three/examples/jsm/loaders/OBJLoader";
 
//https://convert3d.org/
export function Avatar(props: JSX.IntrinsicElements["group"]) {
  const scene = useLoader(OBJLoader, AVATAR_MODEL);
  console.log({scene})
  return <primitive object={scene} />
}

//useGLTF.preload("/646d9dcdc8a5f5bddbfac913_Notextures-transformed.glb");
